# Generated by Django 4.0.5 on 2022-06-09 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='create_at',
            field=models.CharField(default=datetime.timezone, max_length=255),
        ),
        migrations.AlterField(
            model_name='customers',
            name='update_at',
            field=models.CharField(default=datetime.timezone, max_length=255),
        ),
    ]
